language: erlang
otp_release:
    - R16B02
before_install:
    - git clone https://github.com/elixir-lang/elixir
    - cd elixir && git checkout v0.12.5 && make && cd ..
before_script:
    - export PATH=`pwd`/elixir/bin:$PATH
    - MIX_ENV=test mix do deps.get
    - MIX_ENV=test mix do deps.compile
script:
    - MIX_ENV=test mix amrita --trace