language: erlang
otp_release: 
  - 17.0
install:
  - git clone git://github.com/rebar/rebar.git
  - cd rebar && ./bootstrap
  - export PATH=$PATH:`pwd` && cd ..
  - sudo apt-get update
  - sudo apt-get -y install erlang
script:
    "make ci"
after_script:
  - export PATH=$PATH:`pwd` && cd ..
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
