language: erlang

otp_release:
    - R16B03-1

before_install:
    - git clone git://github.com/elixir-lang/elixir --depth 1
    - make -C elixir

before_script:
    - "export PATH=`pwd`/elixir/bin:$PATH"
    - MIX_ENV=test mix do deps.get
script:
    - MIX_ENV=test mix test